package com.dynamodb.springbootdynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.ToString;


@Data
@DynamoDBTable(tableName = "product")
@ToString
public class Product {

    @DynamoDBHashKey
    private String sku;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private int price;
    @DynamoDBAttribute
    private int quantity;

}
